### ISSUE TITLE
Function normalizeFullClassName assert fails when selecting transient id

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/presentation#775] opened 2024-11-12 15:26 UTC
Hi. Please make sure the selection of transient element ids works properly.

The following assert fails in pineapple (call originates from measure-tools-react) when we attempt to select a measurement (transient element).
https://github.com/iTwin/presentation/blob/9374049632acf91de7018d02b49660b11e53caa6/packages/shared/src/shared/Utils.ts#L27

Here is what the function receives as argument:
![Image](https://github.com/user-attachments/assets/ee5ea2d5-7a36-46cb-a22c-6bfb711de56e)

Not sure about this package specifically, but selecting transient elements use to work properly in the past.

Thanks,
Alex

**Comment by grigasp** [comment] 2024-11-12 15:39
Hi, @a-gagnon. The problem is already fixed with [this PR](https://github.com/iTwin/presentation/pull/765) and released with `@itwin/unified-selection@1.1.1`. I guess we'll need Pineapple to bump their dependency? @jason-crow

**Comment by grigasp** [comment] 2024-11-13 05:41
@a-gagnon, I'll keep this issue open until you confirm the issue is fixed. Please get back to us when Pineapple consumes the fix and you give it a go.

**Comment by grigasp** [comment] 2024-11-22 08:13
didn't get any response for a week - closing the issue

**Closed by grigasp** 2024-11-22 08:13 UTC
Labels: bug, presentation
